### PR TITLE
One fix and one improvement

### PR DESCRIPTION
**Pull request by tschoonj**
* Use conda to install sregistry
* Use sudo to untar go

### CODE REVIEW

**Comment by tschoonj** [comment]
@vsoch same problem here btw: https://circleci.com/gh/singularityhub/circle-ci/42

**Comment by vsoch** [comment]
Using conda would be great! If you want to rebase with the (now Circle Orb based) recipe, I'd be glad to review this.

**Comment by tschoonj** [comment]
Btw can I remove setup.sh now?

**Comment by tschoonj** [comment]
Aha you're too fast for me... another rebase coming up!

**Comment by vsoch** [comment]
Question - does conda install support targeting a group akin to pip? Could we also target "all" ?

**Comment by vsoch** [comment]
E.g.

```bash
conda install -y -c defaults -c conda-forge sregistry[all]
```

**Comment by vsoch** [comment]
I also added a filter to ignore updates to master branch, doesn't make much sense given a repo with a pull request to update model.

**Comment by tschoonj** [comment]
Hmmm not really, they have something called variants but that is for if you want `mpi4py` built against OpenMPI or mpich2.

Basically when I created the `sregistry` recipe, I just added as many dependencies as were available on Conda-forge. Think the only backend that doesn't work now is the OpenStack one, but need to check that.

**Comment by vsoch** [comment]
Ah okay, then that works! Ready for merge?

**Comment by tschoonj** [comment]
absolutely!

**Pull request merged**
